#!/bin/bash

# Frontend Deployment Script for Gorweld
# This script prepares and deploys the frontend to production

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

print_header() {
    echo -e "\n${BLUE}=== $1 ===${NC}\n"
}

print_status() {
    echo -e "${GREEN}✓${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

print_header "Gorweld Frontend Deployment"

# Configuration
read -p "Enter production API URL (e.g., https://api.gorweld.com/api): " API_URL
read -p "Enter treasury wallet address: " TREASURY_ADDRESS
read -p "Deploy to directory (default: ./dist): " DEPLOY_DIR
DEPLOY_DIR=${DEPLOY_DIR:-./dist}

echo ""
print_header "Configuration Summary"
echo "API URL: $API_URL"
echo "Treasury: $TREASURY_ADDRESS"
echo "Deploy Directory: $DEPLOY_DIR"
echo ""

read -p "Is this correct? (y/n): " CONFIRM
if [ "$CONFIRM" != "y" ]; then
    echo "Deployment cancelled."
    exit 0
fi

# Create deployment directory
print_status "Creating deployment directory..."
mkdir -p "$DEPLOY_DIR"

# Copy production config
print_status "Configuring production settings..."
cat > "$DEPLOY_DIR/config.js" << EOF
/**
 * Gorweld Production Configuration
 * Auto-generated by deploy-frontend.sh
 */

const GorweldConfig = {
    api: {
        development: 'http://localhost:3000/api',
        production: '$API_URL',
        
        getBaseURL: function() {
            const isLocalhost = window.location.hostname === 'localhost' || 
                              window.location.hostname === '127.0.0.1';
            return isLocalhost ? this.development : this.production;
        }
    },
    
    solana: {
        network: 'mainnet-beta',
        rpcUrl: 'https://api.mainnet-beta.solana.com',
        treasuryAddress: '$TREASURY_ADDRESS',
        paymentAmount: 1,
        commitment: 'confirmed'
    },
    
    features: {
        cardSubmission: true,
        walletConnection: true,
        cardEditing: true
    },
    
    upload: {
        maxImageSize: 5 * 1024 * 1024,
        maxVideoSize: 20 * 1024 * 1024,
        allowedImageTypes: ['image/png', 'image/jpeg', 'image/jpg', 'image/webp'],
        allowedVideoTypes: ['video/webm', 'video/mp4'],
        maxMediaFiles: 5
    },
    
    ui: {
        ctaHeading: 'Submit Your Project to Gorweld',
        ctaDescription: 'Showcase your project to the Gorbagana ecosystem. First-come, first-serve.',
        connectWalletText: 'Connect Wallet',
        animationDuration: 300
    },
    
    validation: {
        projectName: {
            minLength: 3,
            maxLength: 50
        },
        projectSubtitle: {
            minLength: 10,
            maxLength: 100
        },
        projectDescription: {
            minLength: 20,
            maxLength: 500
        },
        projectUrl: {
            pattern: /^https?:\/\/.+/
        }
    }
};

Object.freeze(GorweldConfig);
Object.freeze(GorweldConfig.api);
Object.freeze(GorweldConfig.solana);
Object.freeze(GorweldConfig.features);
Object.freeze(GorweldConfig.upload);
Object.freeze(GorweldConfig.ui);
Object.freeze(GorweldConfig.validation);
EOF

# Copy main HTML file
print_status "Copying HTML files..."
cp index.html "$DEPLOY_DIR/"

# Copy assets if they exist
if [ -d "assets" ]; then
    print_status "Copying assets..."
    cp -r assets "$DEPLOY_DIR/"
fi

if [ -d "Screenshots-videos" ]; then
    print_status "Copying media files..."
    cp -r Screenshots-videos "$DEPLOY_DIR/"
fi

# Copy logo if exists
if [ -f "Gorweld-Logo.png" ]; then
    cp Gorweld-Logo.png "$DEPLOY_DIR/"
fi

# Minify JavaScript (optional - requires uglify-js)
if command -v uglifyjs &> /dev/null; then
    print_status "Minifying JavaScript..."
    # Extract and minify inline JavaScript if needed
    print_warning "Manual JavaScript minification recommended for production"
else
    print_warning "uglify-js not found. Skipping JavaScript minification."
fi

# Create .htaccess for Apache (if needed)
print_status "Creating .htaccess..."
cat > "$DEPLOY_DIR/.htaccess" << 'EOF'
# Enable compression
<IfModule mod_deflate.c>
    AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css text/javascript application/javascript
</IfModule>

# Enable caching
<IfModule mod_expires.c>
    ExpiresActive On
    ExpiresByType image/jpg "access plus 1 year"
    ExpiresByType image/jpeg "access plus 1 year"
    ExpiresByType image/png "access plus 1 year"
    ExpiresByType image/webp "access plus 1 year"
    ExpiresByType video/webm "access plus 1 year"
    ExpiresByType video/mp4 "access plus 1 year"
    ExpiresByType text/css "access plus 1 month"
    ExpiresByType application/javascript "access plus 1 month"
</IfModule>

# Security headers
<IfModule mod_headers.c>
    Header set X-Content-Type-Options "nosniff"
    Header set X-Frame-Options "SAMEORIGIN"
    Header set X-XSS-Protection "1; mode=block"
</IfModule>
EOF

# Create deployment info file
print_status "Creating deployment info..."
cat > "$DEPLOY_DIR/DEPLOYMENT_INFO.txt" << EOF
Gorweld Frontend Deployment
===========================

Deployed: $(date)
API URL: $API_URL
Treasury: $TREASURY_ADDRESS

Files:
- index.html (main application)
- config.js (production configuration)
- .htaccess (server configuration)

Deployment Steps:
1. Upload all files to your web server
2. Ensure config.js is loaded before index.html scripts
3. Test wallet connection
4. Test card submission flow
5. Verify API connectivity

Support:
- Check browser console for errors
- Verify API is accessible
- Ensure treasury address is correct
EOF

print_header "Deployment Complete!"

echo "📦 Files prepared in: $DEPLOY_DIR"
echo ""
echo "📋 Next Steps:"
echo "   1. Upload files to your web server"
echo "   2. Test the deployment:"
echo "      - Open https://gorweld.com in browser"
echo "      - Check browser console for errors"
echo "      - Test wallet connection"
echo "      - Test card submission"
echo ""
echo "🔍 Verification:"
echo "   - API URL configured: $API_URL"
echo "   - Treasury address: $TREASURY_ADDRESS"
echo "   - Config file: $DEPLOY_DIR/config.js"
echo ""
echo "✅ Frontend deployment prepared successfully!"
